#!/bin/sh
# 使い捨てPostgreSQL向け。migration所有者とWeb DML roleの境界を実SQLで検証する。
set -eu

: "${POSTGRES_HOST:?POSTGRES_HOST is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_MIGRATION_USER:?POSTGRES_MIGRATION_USER is required}"
: "${POSTGRES_MIGRATION_PASSWORD:?POSTGRES_MIGRATION_PASSWORD is required}"
: "${POSTGRES_APP_USER:?POSTGRES_APP_USER is required}"
: "${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD is required}"

export PGPASSWORD="$POSTGRES_MIGRATION_PASSWORD"
psql -v ON_ERROR_STOP=1 --host="$POSTGRES_HOST" --username="$POSTGRES_MIGRATION_USER" --dbname="$POSTGRES_DB" <<'SQL'
CREATE TABLE role_boundary_probe (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value text NOT NULL
);
INSERT INTO role_boundary_probe (value) VALUES ('created-by-migrator');
SQL

export PGPASSWORD="$POSTGRES_APP_PASSWORD"
psql -v ON_ERROR_STOP=1 --host="$POSTGRES_HOST" --username="$POSTGRES_APP_USER" --dbname="$POSTGRES_DB" <<'SQL'
SELECT value FROM role_boundary_probe;
INSERT INTO role_boundary_probe (value) VALUES ('inserted-by-app');
UPDATE role_boundary_probe SET value = 'updated-by-app' WHERE value = 'inserted-by-app';
DELETE FROM role_boundary_probe WHERE value = 'updated-by-app';
SQL

if psql -v ON_ERROR_STOP=1 --host="$POSTGRES_HOST" --username="$POSTGRES_APP_USER" --dbname="$POSTGRES_DB" \
    --command="CREATE TABLE app_must_not_create_tables (id integer)" >/dev/null 2>&1; then
    echo "[db-role-test] application role unexpectedly created a table" >&2
    exit 1
fi

export PGPASSWORD="$POSTGRES_MIGRATION_PASSWORD"
psql -v ON_ERROR_STOP=1 --host="$POSTGRES_HOST" --username="$POSTGRES_MIGRATION_USER" --dbname="$POSTGRES_DB" \
    --command="DROP TABLE role_boundary_probe"
echo "[db-role-test] migration DDL, app DML and app DDL denial verified"
