# Generated by Django 5.2.15 on 2026-09-10 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_sitesetting_enable_motion_sitesetting_theme_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='accent_color',
            field=models.CharField(default='#2563eb', help_text='明るいテーマで使う色。ボタンの背景にはこの色をそのまま使い、本文中のリンクはテーマの背景に対して読みにくい場合だけ明るさを自動調整します。', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', '色は #rgb または #rrggbb の形式で指定してください。')], verbose_name='アクセント色'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='accent_color_dark',
            field=models.CharField(default='#60a5fa', help_text='Midnight などの暗いテーマで使う色。どちらを使うかはテーマの明暗で決まります。', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', '色は #rgb または #rrggbb の形式で指定してください。')], verbose_name='アクセント色（ダーク）'),
        ),
    ]
